InterviewScheduler/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scheduler.urls')),
]

scheduler/urls.py
from django.urls import path, re_path

from . import views

app_name = 'scheduler'

urlpatterns = [
    path('', views.index, name = "index"),
    path('schedule', views.schedule_interview, name = "schedule_interview"),
    path('timeline', views.timeline, name = "timeline"),
    path(r'^/<int:interview_id>/$', views.interview_page, name = "interview_page"),
    path('edit', views.edit_interview, name = "edit_interview")
]

scheduler/models.py
from django.db import models

# Importing Models
from django.contrib.auth.models import User

# Create your models here.
class interview(models.Model):
    interview_name = models.CharField(verbose_name = "Interview Name", max_length = 100)
    start_time = models.DateTimeField(verbose_name = "Start Time")
    end_time = models.DateTimeField(verbose_name = "End Time")
    participant = models.ManyToManyField(User)

    def __str__(self):
        return self.interview_name

scheduler/views.py
from django.shortcuts import redirect, render
from django.contrib import messages 
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from django.core.mail import send_mail

from datetime import date, datetime, timedelta
import pytz

# Models
from django.contrib.auth.models import User 
from .models import interview

# Create your views here.

#Function to check availability of all the participants
def check_availability(scheduled_interviews, start_time, end_time):
    #Set of tuples of start time, end time for all the scheduled interviews
    scheduled_timings = list(interview.objects.filter(id__in = scheduled_interviews).values_list('start_time', 'end_time'))
    
    for start, end in scheduled_timings:
        if start <= start_time < end or start < end_time < end or (start_time <= start < end <= end_time):
            return True
    
    return False

#Function to convert datetime from naive to offset
def convert_datetime_to_offset(naive_time):
    timezone = pytz.timezone("UTC")
    offset_time = timezone.localize(datetime.strptime(naive_time, '%Y-%m-%dT%H:%M'))

    return offset_time

#Function to convert datetime from offset to naive
def convert_datetime_to_naive(offset_time):
    offset_time = str(offset_time)
    naive_time = offset_time[:10] + "T" +  offset_time[11:-6]

    return naive_time

def index(request):
    return render(request, 'scheduler/index.html')

def schedule_interview(request):
    if request.method == "POST":
        # Needs to be update THREAD 2.0
        new_interview_name = request.POST['meet_name']
        participants_email = request.POST.getlist('email')
        start_time = request.POST['start_time']
        end_time = request.POST['end_time']

        start_time = convert_datetime_to_offset(start_time)
        end_time = convert_datetime_to_offset(end_time)

        #Checks
        #Validating email
        try:
            participants = set()

            for email in participants_email:
                participant = User.objects.get(email = email)
                participants.add(participant)
                
        except ObjectDoesNotExist:
            messages.error(request, "Oops! One or more invalid Email ID. Please try again")
            return redirect('/')
                
        
        #Check for the number of participants
        if len(participants) < 2:
            messages.error(request, "Please select more than 2 distinct participants.")
            return redirect('/')
        

        #Check the Availability of participants
        #All the Interview id of the participants
        scheduled_interviews = User.objects.filter(email__in = participants_email).values_list('interview', flat=True)
        
        if check_availability(scheduled_interviews, start_time, end_time):
            messages.error(request, "One or more participants will be busy during the selected time period. Please try a different time period.")
            return redirect('/')

        #After validating all checks
        #Add to Database
        new_interview = interview(interview_name = new_interview_name, start_time = start_time, end_time = end_time)
        new_interview.save()

        for participant in participants:
            new_interview.participant.add(participant)

        messages.success(request, "Interview Scheduled successfully")
        
        send_mail(
            subject = "Interview Scheduled",
            message = "Your interview is scheduled.",
            from_email = settings.EMAIL_HOST_USER,
            recipient_list = participants_email
        )
        return redirect('/')

    return redirect('/')

def timeline(request):
    interviews = interview.objects.filter(end_time__date__gt = date.today() - timedelta(days = 1))
    
    context ={
        'interviews': interviews
    }

    return render(request, 'scheduler/timeline.html', context)

def interview_page(request, interview_id):
    schedule_interview = interview.objects.get(id = interview_id)

    schedule_interview.start_time = convert_datetime_to_naive(schedule_interview.start_time)
    schedule_interview.end_time = convert_datetime_to_naive(schedule_interview.end_time)

    context = {
        'interview': schedule_interview
    }
    return render(request, 'scheduler/interview.html', context)

def edit_interview(request):
    if request.method == "POST":
        if 'edit_interview' in request.POST:
            interview_id = request.POST['interview_id']
            edit_interview = request.POST['meet_name']
            participants_email = request.POST.getlist('email')

            start_time = request.POST['start_time']
            end_time = request.POST['end_time']

            #Converting naive datetime to offset
            start_time = convert_datetime_to_offset(start_time)
            end_time = convert_datetime_to_offset(end_time)
            
            #Checks
            #Validating email
            try:
                participants = set()

                for email in participants_email:
                    participant = User.objects.get(email = email)
                    participants.add(participant)
                    
            except ObjectDoesNotExist:
                messages.error(request, "Oops! One or more invalid Email ID. Please try again")
                return redirect('/')
                    
            
            #Check for the number of participants
            if len(participants) < 2:
                messages.error(request, "Please select more than 2 distinct participants.")
                return redirect('/')
            

            #Check the Availability of participants
            #All the Interview id of the participants
            scheduled_interviews = User.objects.filter(email__in = participants_email).values_list('interview', flat=True)
            
            if check_availability(scheduled_interviews, start_time, end_time):
                messages.error(request, "One or more participants will be busy during the selected time period. Please try a different time period.")
                return redirect('/')

            #After validating all checks
            #Modify the database
            meet = interview.objects.get(id = interview_id)
            meet.interview_name = edit_interview
            meet.start_time = start_time
            meet.end_time = end_time

            meet.participant.clear()
            for participant in participants:
                meet.participant.add(participant)
            
            meet.save()
            
            send_mail(
                subject = "Your scheduled interview has an update!",
                message = "Your interview is updated.",
                from_email = settings.EMAIL_HOST_USER,
                recipient_list = participants_email
            )

            messages.success(request, "Interview edited successfully")
            return redirect('/timeline')

        elif 'delete_interview' in request.POST:
            interview_id = request.POST['interview_id']
            meet = interview.objects.get(id = interview_id)

            participants_email = list()
            for participant in meet.participant.all():
                participants_email.append(participant.email)

            meet.delete()

            send_mail(
                subject = "Your scheduled interview has an update!",
                message = "Your interview is updated.",
                from_email = settings.EMAIL_HOST_USER,
                recipient_list = participants_email
            )

            messages.success(request, "Interview deleted successfully")
            return redirect('/timeline')


    return redirect('/timeline')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <script src="https://cdn.tailwindcss.com"></script>

    <!-- Manual CSS and JS-->
    <script src="{% static 'base.js' %}" type="text/javascript" defer></script> 
    <title>{% block title %} Interview Scheduler {% endblock %} </title>
    
    {% block style %}
    <style>
        .success{
            color: #155724;
            background-color: #d4edda;
            border-color: #c3e6cb;
        }
        .error{
            color: #721c24;
            background-color: #f8d7da;
            border-color: #f5c6cb;
        }
    </style>
    {% endblock %}
    
    {% block script %}
    {% endblock %}
</head>
<body>  

    {% for message in messages  %}            
    <div class="{{ message.tags }} message{{ forloop.counter }} my-6 mx-48 rounded-lg px-10 py-3 flex justify-between" role="alert">
        <p><strong>Message : </strong> {{ message }}</p>
        <span onclick="removeParent(this)" id="message{{ forloop.counter }}" class="cursor-pointer font-bold">x</span>
    </div>
    {% endfor %}

    {% block navbar %}
    <div class="flex flex-row justify-evenly my-4 mx-4 md:mx-32 lg:mxpy-80">
        <a href="/" class="text-xl font-semibold hover:text-blue-700">Schedule</a>
        <p class="text-xl font-semibold">|</p>
        <a href="/timeline" class="text-xl font-semibold hover:text-blue-700">Timeline</a>
    </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
    
    {% block footer %}
    {% endblock %}

</body>
</html>

templates/scheduler/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Interview Scheduler {% endblock %}

{% block script %}
<script src="{% static 'scheduler/style.js' %}" type="text/javascript" defer></script>
{% endblock %}

{% block content %}

<div class="mx-64 my-8">
    <form action="/schedule" method="POST" onsubmit="handleDateValidation(event)">
        {% csrf_token %}

        <div class="my-6">
            <label for="meet_name" class="block text-base mb-2">Meeting Name</label>
            <input type="text" name="meet_name" placeholder="Meet Name" class="bg-gray-50 border border-gray-300 text-slate-700 text-sm rounded-lg focus:border-blue-500 block w-full p-2.5" required>
        </div>

        <div id="container" class="grid grid-cols-2 gap-6 my-6">
            <div>
                <label for="email1" class="block text-base mb-2">Participant 1</label>
                <input type="email" name="email" placeholder="Mail Address" class="bg-gray-50 border border-gray-300 text-slate-700 text-sm rounded-lg focus:border-blue-500 block w-full p-2.5" required>    
            </div>
            
            <div>
                <label for="email1" class="block text-base mb-2">Participant 2</label>
                <input type="email" name="email" placeholder="Mail Address" class="bg-gray-50 border border-gray-300 text-slate-700 text-sm rounded-lg focus:border-blue-500 block w-full p-2.5" required>
            </div>
        </div>
        
        <a onClick="addParticipant()" class="cursor-pointer text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 my-3 text-center">Add participant</a>

        <div class="grid grid-cols-2 gap-6 my-6">
            <div>
                <label for="email1" class="block text-base mb-2">Start Time</label>
                <input type="datetime-local" name="start_time" id="startTime" class="bg-gray-50 border border-gray-300 text-slate-700 text-sm rounded-lg focus:border-blue-500 block w-full p-2.5" required>    
            </div>
            
            <div>
                <label for="email1" class="block text-base mb-2">End Time</label>
                <input type="datetime-local" name="end_time" id="endTime" class="bg-gray-50 border border-gray-300 text-slate-700 text-sm rounded-lg focus:border-blue-500 block w-full p-2.5" required>
                <p id="error" class="text-red-500 text-sm font-medium"></p>
            </div>
        </div>
        
        <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 my-3 text-center">Schedule</button>
    </form>
</div>
{% endblock %}

templates/scheduler/interview.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Interview {% endblock %}

{% block script %}
<script src="{% static 'scheduler/style.js' %}" type="text/javascript" defer></script>
{% endblock %}

{% block content %}
<div class="mx-64 my-8">
    <form action="/edit" method="POST" onsubmit="handleDateValidation(event)">
        {% csrf_token %}

        <!-- Change Placeholder -->
        <div class="my-6">
            <label for="meet_name" class="block text-base mb-2">Meeting Name</label>
            <input type="text" name="meet_name" placeholder="Meet Name" value="{{ interview.interview_name }}" class="bg-gray-50 border border-gray-300 text-slate-700 text-sm rounded-lg focus:border-blue-500 block w-full p-2.5" required>
        </div>

        <div id="container" class="grid grid-cols-2 gap-6 my-6">
            {% for user in interview.participant.all %}
            <div class="participant{{ forloop.counter }}">
                <label for="email" class="block text-base mb-2">Participant Mail</label>
                <div class="flex">
                    <input type="email" name="email" placeholder="Please Enter Mail" value="{{ user.email }}" class="flex-1 bg-gray-50 border border-gray-300 text-slate-700 text-sm rounded-l-lg focus:border-blue-500 block w-full p-2.5" required>
                    <span onClick="removeParent(this)" id="participant{{ forloop.counter }}" class="cursor-pointer bg-gray-200 inline-flex items-center px-3 text-sm text-gray-900 rounded-r-lg border border-l-0 border-gray-300">
                        X
                    </span>
                </div>
                    
            </div>
            {% endfor %}
        </div>

        <a onClick="addParticipant()" class="cursor-pointer text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 my-3 text-center">Add participant</a>

        <div class="grid grid-cols-2 gap-6 my-6">
            <div>
                <label for="email1" class="block text-base mb-2">Start Time</label>
                <input type="datetime-local" name="start_time" id="startTime" value="{{ interview.start_time }}" class="bg-gray-50 border border-gray-300 text-slate-700 text-sm rounded-lg focus:border-blue-500 block w-full p-2.5" required>    
            </div>
            
            <div>
                <label for="email1" class="block text-base mb-2">End Time</label>
                <input type="datetime-local" name="end_time" id="endTime" value="{{ interview.end_time }}" class="bg-gray-50 border border-gray-300 text-slate-700 text-sm rounded-lg focus:border-blue-500 block w-full p-2.5" required>
                <p id="error" class="text-red-500 text-sm font-medium"></p>
            </div>
        </div>
        <input type="hidden" name="interview_id" value="{{ interview.id }}"/>
        
        <button type="submit" name="edit_interview" class="text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 my-3 text-center">Edit</button>
        <button type="submit" name="delete_interview" class="text-white bg-red-700 hover:bg-red-800 font-medium rounded-lg text-sm px-5 py-2.5 my-3 text-center">Delete</button>
    </form>
</div>
{% endblock %}

templates/scheduler/timeline.html
{% extends 'base.html' %}

{% block title %} Interview Timeline {% endblock %}
{% block content %}

<div class="flex flex-col ">
    {% if interviews %}
        {% for interview in interviews %}
        <div class="flex flex-col mx-44 my-8 grid-rows-4 block p-6 bg-white rounded-lg border border-gray-200 shadow-md hover:bg-slate-50">
            <div class="flex flex-row justify-between my-1">
                <h2 class="mb-2 text-2xl font-bold text-gray-900">{{ interview.interview_name }}</h2>
                <a href="{% url 'scheduler:interview_page' interview.id %}" class="text-white bg-blue-700 hover:bg-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Edit</a>
            </div>
        
            <div class="flex flex-row font-normal text-gray-800 my-1">
                <p class="mx-4 ml-0">{{ interview.start_time }}</p>
                <p class="mx-4">-</p>
                <p class="mx-4">{{ interview.end_time }}</p>
            </div>
            
            
            <div class="my-8">
                <p class="">Participants</p>
                <hr width="12%" style="height:4px; background-color:#1d4ed8;">
                
                <div class="flex flex-row flex-wrap mt-4">
                    {% for user in interview.participant.all %}
                    <div>
                        <button type="button" class="text-gray-900 bg-slate-50 bg-white border border-gray-300 hover:bg-gray-100 font-medium rounded-lg text-sm px-12 py-2.5 mr-6 mb-4">
                            <p>{{ user.first_name }} {{ user.last_name }}</p>
                            <p>{{ user.email }}</p>
                        </button>
                    </div>
                    {% endfor %}
                </div>
            </div>
            </div>
            
        </div>
        {% endfor %}
    {% else %}
    <div class="flex flex-col mx-44 my-8 grid-rows-4 block p-6 bg-white rounded-lg border border-gray-200 shadow-md hover:bg-slate-50">
        <p>No Interview Scheduled.</p>
    </div>
    {% endif %}
</div>
{% endblock %}